Saml assertion flow - display error to user if assertion can't be loaded
NVandenBossche/salesforce-iam-flows pull request #4
Opened 2021-05-09 04:25 UTC by LawrenceLoz

If assertion not present, readFileSync() was failing with uncaught exception. Added try/catch and an more meaningful error to be displayed back on page

Also removed data/ from gitignore to reduce confusion for anyone adding their own assertion and pushing to heroku

2021-05-11 14:06 UTC, NVandenBossche commented on Server.js
> +    }
Your parameter for catch is 'e' and you pass 'error' to the response page :-)
Also, small typo in the log message: 'Erorr' instead of 'Error'.

2021-05-11 14:07 UTC, NVandenBossche requested changes
See detailed comments on 'catch'

2021-05-11 14:49 UTC, LawrenceLoz commented on Server.js
> +    }
Yeah this is sorted in the second commit https://github.com/NVandenBossche/salesforce-iam-flows/pull/4/commits/5610ac83548dcf709dbff525d0025922b9ac8cdc. And try/catch added to the readFileSync call in samlassert which was failing when there's no file

2021-05-23 19:23 UTC, NVandenBossche commented on Server.js
> +    }
Missed that :-) That's what you get when reviewing code on your phone. Thanks, I'll merge!

2021-05-23 19:24 UTC, merged

2021-05-24 06:27 UTC, LawrenceLoz commented on Server.js
> +    }
Thanks @NVandenBossche and might have been my mistake - not sure whether I'd definitely pushed latest commit before creating the PR