Readme suggestions
NVandenBossche/salesforce-iam-flows pull request #6
Opened 2021-05-09 04:43 UTC by LawrenceLoz

A few suggested changes here:

- Change to the openssl parameter syntax, looks like a typo? (I generated using nodes and cert and key behave as expected)
- Change to suggested callback URL for Heroku to remove port specification. Using the suggested version with port specified I wasn't able to get Heroku to recognise the callback. Reading a bit (e.g. https://stackoverflow.com/questions/28706180/setting-the-port-for-node-js-server-on-heroku) I think this is because Heroku expects to always use default ports, and even with the https.createServer() function it doesn't seem to be listening at port 8081 - using original callback URL I can see the network call to the callback URL but no indication Heroku has recognised this. Using a callback URL of https://my-heroku-app.herokuapp.com:443/oauthcallback works, as does https://my-heroku-app.herokuapp.com/oauthcallback
- Recommendation to enable device flow in connected app

2021-05-09 04:45 UTC, LawrenceLoz commented
Not sure whether I'm missing something around Heroku config or anything else to get the listener at port 8081 to work - curious if this works for you?

2021-05-11 13:58 UTC, NVandenBossche commented on README.md
> +-   Run the following command in the root of the cloned repository: `openssl req -x509 -newkey rsa:2048 -keyout key.pem -out server.crt -days 365 -nodes`
The -nodes flag is deprecated since OpenSSL 3.0. See https://www.openssl.org/docs/manmaster/man1/openssl-req.html

2021-05-11 14:01 UTC, NVandenBossche requested changes
Thanks, indeed the port was incorrect :-) Still some changes I need to do to the readme + add some audio to the instruction video.

The only thing I would change (back) is the nodes/noenc (nodes is deprecated since 3.0)

2021-05-11 14:33 UTC, LawrenceLoz commented on README.md
> +-   Run the following command in the root of the cloned repository: `openssl req -x509 -newkey rsa:2048 -keyout key.pem -out server.crt -days 365 -nodes`
Ah yes you're right, although openssl 3.0 isn't yet offered as a stable version (https://www.openssl.org/source/). Using v1.1.1 I get an "Unrecognized flag" error with -noenc... I could change to mention both versions with a description of why each one might be needed?

2021-05-23 19:22 UTC, NVandenBossche commented
Closing because I made the changes manually myself

2021-05-23 19:22 UTC, closed without merging